#pragma once

#define ID_VERSION_INFO 1
#define IDR_PREVIEW_SCRIPT 101
#define IDR_PREVIEW_STYLE 102
#define IDR_HIGHLIGHT_SCRIPT 103
#define IDR_HIGHLIGHT_CMAKE_SCRIPT 104
#define IDR_HIGHLIGHT_DOS_SCRIPT 105
#define IDR_HIGHLIGHT_LISP_SCRIPT 106
#define IDR_HIGHLIGHT_POWERSHELL_SCRIPT 107
#define IDR_HIGHLIGHT_PROPERTIES_SCRIPT 108
